### ISSUE TITLE
Punch-card stuck after

### ISSUE THREAD

**Issue by RJDan** [koffeinfrei/punch-card#3] opened 2023-01-17 04:41 UTC
Hello,
This looks like a really cool tool. I tried it out for a few moments and I think Ive messed something up.
I added an entry with ``` punch-card now-03:00 -p Personal:Computers```
and now I've got the following error ....
```
The 'to' entry Store::Entry(@id="8a06cc06-efac-4cbd-ab1e-db382a8cab51", @type=Start, @time=2023-01-17 00:01:20.374000000 UTC, @project="Personal:Computers") is not of type Stop, although it should be
```

I can't add anything else. How could I correct?

**Comment by sarahjcotton** [comment] 2023-12-11 15:33
@RJDan If you install sqlite3 you can open the data.db file then run a query to remove the entry where a new start was added before the last stop should have been run. Probably a bit late now but this might help someone else!

**Comment by koffeinfrei** [comment] 2023-12-18 13:30
Duplicate of https://github.com/koffeinfrei/punch-card/issues/2

**Closed as completed by koffeinfrei** 2023-12-18 13:30 UTC
